const content = {
    en: {
	home: "Home",
        explore : "Explore",
        notif: "Notifications",
        message: "Messages",
        bookmark: "Bookmarks",
        lists: "Lists",
        profile: "Profile",
        more : "More",
        twitter: "Twitter",
        type_here: "What's happening",
        minut: "min",
        hour: "h",
        search: "Search Twitter",
        trends: "Trends for you",
        show_more: "Show more",
        more_news : "You might like",
        follow: "Follow",
        service: "Terms of service",
        privacy: "Privacy Policy",
        cookie: "Cookie Policy",
        imprint: "Imprint",
        ads_info: "Ads Info",        
	},

	ru: {
        home: "Главная",
        explore : "Поиск",
        notif: "Удевомление",
        message: "Сообщения",
        bookmark: "Закладки",
        lists: "Списки",
        profile: "Профиль",
        more : "Еще",
        twitter: "Твитнуть",
        type_here: "Что нового",
        minut: "мин",
        hour: "ч",
        search: "Поиск в Твиттере",
        trends: "Вам может понравиться ",
        show_more: "Показать еще",
        more_news : "Кого читать",
        follow: "Читать",
        service: "Условия обслуживания",
        privacy: "Политика конфиденциальности",
        cookie: "Политика использования файлов cookie",
        imprint: "Отпечаток",
        ads_info: "Информация о реклам",   
	},
	
};

export default content;